import { boolean, integer, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const user = pgTable("user", {
  id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("emailVerified").notNull().default(false), image: text("image"), createdAt: timestamp("createdAt").notNull(), updatedAt: timestamp("updatedAt").notNull(),
});
export const session = pgTable("session", { id: text("id").primaryKey(), expiresAt: timestamp("expiresAt").notNull(), token: text("token").notNull().unique(), createdAt: timestamp("createdAt").notNull(), updatedAt: timestamp("updatedAt").notNull(), ipAddress: text("ipAddress"), userAgent: text("userAgent"), userId: text("userId").notNull() });
export const account = pgTable("account", { id: text("id").primaryKey(), accountId: text("accountId").notNull(), providerId: text("providerId").notNull(), userId: text("userId").notNull(), accessToken: text("accessToken"), refreshToken: text("refreshToken"), idToken: text("idToken"), accessTokenExpiresAt: timestamp("accessTokenExpiresAt"), refreshTokenExpiresAt: timestamp("refreshTokenExpiresAt"), scope: text("scope"), password: text("password"), createdAt: timestamp("createdAt").notNull(), updatedAt: timestamp("updatedAt").notNull() });
export const verification = pgTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expiresAt").notNull(), createdAt: timestamp("createdAt"), updatedAt: timestamp("updatedAt") });

export const institutions = pgTable("pax_institutions", { id: uuid("id").primaryKey(), name: text("name").notNull(), abbreviation: text("abbreviation").notNull().unique(), country: text("country"), logoUrl: text("logo_url"), verificationDomain: text("verification_domain"), viceChancellorName: text("vice_chancellor_name"), viceChancellorSignatureUrl: text("vice_chancellor_signature_url"), registrarName: text("registrar_name"), registrarSignatureUrl: text("registrar_signature_url"), programmeContractAddress: text("programme_contract_address"), status: text("status").notNull().default("pending"), subscriptionStatus: text("subscription_status").notNull().default("not_configured"), createdByUserId: text("created_by_user_id").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() });
export const institutionMembers = pgTable("pax_institution_members", { id: uuid("id").primaryKey(), institutionId: uuid("institution_id").notNull(), userId: text("user_id").notNull(), role: text("role").notNull().default("issuer"), status: text("status").notNull().default("active"), invitedByUserId: text("invited_by_user_id"), createdAt: timestamp("created_at", { withTimezone: true }).notNull() });
export const institutionDeans = pgTable("pax_institution_deans", { id: uuid("id").primaryKey(), institutionId: uuid("institution_id").notNull(), facultyName: text("faculty_name").notNull(), deanName: text("dean_name").notNull(), signatureUrl: text("signature_url"), status: text("status").notNull().default("active"), createdAt: timestamp("created_at", { withTimezone: true }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() });
export const auditLogs = pgTable("pax_audit_logs", { id: uuid("id").primaryKey(), institutionId: uuid("institution_id"), actorUserId: text("actor_user_id").notNull(), action: text("action").notNull(), targetUserId: text("target_user_id"), metadata: text("metadata").notNull().default("{}"), createdAt: timestamp("created_at", { withTimezone: true }).notNull() });
