import { registerSchool } from "@/app/actions/institutions";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import { redirect } from "next/navigation";

export default async function RegisterSchoolPage() {
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session?.user) redirect("/sign-in");
  return <main className="min-h-screen bg-slate-950 text-white"><div className="mx-auto flex max-w-6xl gap-8 p-6 md:p-10"><aside className="hidden w-56 shrink-0 flex-col gap-3 md:flex"><div className="mb-8 text-xl font-semibold">PAX <span className="text-emerald-400">Credential Platform</span></div><a className="rounded-xl bg-white/10 px-4 py-3 text-sm" href="/register-school">Register school</a><a className="rounded-xl px-4 py-3 text-sm text-slate-300 hover:bg-white/10" href="/">Dashboard</a><a className="rounded-xl px-4 py-3 text-sm text-slate-300 hover:bg-white/10" href="/">Issue credentials</a></aside><section className="w-full max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-400">School onboarding</p><h1 className="mt-3 text-4xl font-semibold">Register your school</h1><p className="mt-3 max-w-xl text-slate-300">Tell us about your institution. PAX will review the submission before enabling credential issuance.</p><form action={registerSchool} className="mt-8 flex flex-col gap-5 rounded-2xl border border-white/10 bg-white/[0.06] p-6"><label className="text-sm font-medium">School name<input name="name" required placeholder="University of Lagos" className="mt-2 w-full rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-white placeholder:text-slate-500" /></label><label className="text-sm font-medium">School abbreviation<input name="abbreviation" required maxLength={15} placeholder="UNILAG" className="mt-2 w-full rounded-xl border border-white/15 bg-white/10 px-4 py-3 uppercase text-white placeholder:text-slate-500" /><span className="mt-1 block text-xs text-slate-400">A short code used to identify your school in the app.</span></label><label className="text-sm font-medium">Country<input name="country" placeholder="Nigeria" className="mt-2 w-full rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-white placeholder:text-slate-500" /></label><label className="text-sm font-medium">Verification domain<input name="verificationDomain" type="url" placeholder="https://verification.yourschool.edu" className="mt-2 w-full rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-white placeholder:text-slate-500" /></label><button className="mt-2 rounded-xl bg-emerald-500 px-5 py-3 font-semibold text-slate-950 hover:bg-emerald-400">Submit school for confirmation</button></form></section></div></main>;
}
